import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://console.gcloud.kt.com/auth/signin/direct")
    page.get_by_test_id("text-input-container").get_by_role("textbox", name="input").click()
    page.get_by_test_id("text-input-container").get_by_role("textbox", name="input").click()
    page.get_by_test_id("text-input-container").get_by_role("textbox", name="input").fill("syjeong@wisewires.com")
    page.get_by_role("textbox", name="password-input").click()
    page.get_by_role("textbox", name="password-input").click()
    page.get_by_role("textbox", name="password-input").fill("wW231202##")
    page.get_by_role("button", name="로그인").click()
    page.get_by_role("link", name="활성 TEST_CREATE_SERVER ID:").click()
    page.get_by_role("button", name="Server", exact=True).click()
    page.locator("button").filter(has_text="Server 생성").click()
    page.get_by_role("radio", name="windows-2019-mssql-2017-std-").click()
    page.get_by_role("radio", name="win19std-sql19std-250718v1").click()
    page.get_by_role("radio", name="windows-2019-mssql-2017-std-").click()
    page.get_by_role("radio", name="32x32-amd 32 32 미정 미정").click()
    page.get_by_role("combobox").click()
    page.get_by_role("option", name="DX-G-GB-A").click()
    page.get_by_role("textbox", name="input").click()
    page.get_by_role("textbox", name="input").fill("server-name-01")
    page.get_by_role("combobox").filter(has_text="vpc 선택").click()
    page.get_by_text("TEST_VPCS29Q (10.0.0.0/8)").click()
    page.get_by_role("combobox").filter(has_text="subnet 선택").click()
    page.locator("html").click()
    page.locator("button").filter(has_text="Volume 생성").click()
    page.get_by_placeholder("Volume 이름을 입력해주세요").click()
    page.locator("input[name=\"name\"]").fill("vo-01")
    page.get_by_placeholder("Volume 설명을 입력해주세요").click()
    page.locator("input[name=\"description\"]").fill("vo-01 desc")
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_text("Data Volume : be 1 (block").click()
    page.get_by_placeholder("Volume 용량을 입력해주세요").click()
    page.get_by_role("dialog", name="Volume 생성").locator("input[name=\"size\"]").fill("128")
    page.get_by_role("button", name="확인").click()
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_test_id("s-select-option-list").get_by_text("DX-G-GB-A").click()
    page.get_by_role("button", name="확인").click()
    page.get_by_text("Volume가 성공적으로 생성되었습니다").click()
    page.get_by_text("Volume 생성 성공").click()
    page.get_by_role("checkbox", name="vo-01 84592172-f1e6-4b59-b4f7").click()
    page.get_by_role("combobox").filter(has_text="subnet 선택").click()
    page.get_by_text("subnet", exact=True).click()
    page.locator("html").click()
    page.locator("button").filter(has_text="Subnet 생성").click()
    page.get_by_placeholder("Subnet 이름을 입력해주세요").click()
    page.locator("input[name=\"name\"]").fill("sub-name-01")
    page.get_by_placeholder("Subnet CIDR을 입력해주세요").click()
    page.locator("input[name=\"cidr\"]").click()
    page.locator("input[name=\"cidr\"]").fill("10.0.0.0/8")
    page.get_by_role("button", name="확인").click()
    page.get_by_text("Subnet 생성 성공").click()
    page.get_by_text("Subnet가 성공적으로 생성되었습니다").click()
    page.get_by_role("combobox").filter(has_text="subnet 선택").click()
    page.get_by_text("sub-name-01 (10.0.0.0/8)").click()
    page.get_by_text("NIC이 없습니다. 신규 생성이 필요합니다").click()
    page.locator("button").filter(has_text="신규 NIC 생성").click()
    page.get_by_placeholder("NIC 이름을 입력해주세요").click()
    page.get_by_placeholder("NIC 이름을 입력해주세요").click()
    page.locator("input[name=\"name\"]").fill("net-inter-01")
    page.locator(".s-checkbox.s-checkbox--medium.s-checkbox--default.s-checkbox--hover > .s-checkbox__input-wrapper > .s-checkbox__checkmark").click()
    page.get_by_placeholder("사설 IP 주소를 입력해주세요").click()
    page.locator("input[name=\"ipAddress\"]").fill("172.168.10.4")
    page.get_by_role("dialog", name="Network Interface(NIC) 생성").click()
    page.get_by_role("columnheader", name="ID").press("F12")
    page.get_by_role("columnheader", name="ID").press("F12")
    page.get_by_role("dialog", name="Network Interface(NIC) 생성").click()
    page.get_by_text("Network Interface(NIC) 생성서버 생성 시, VPC, Subnet, Security Group, 사설 IP를 포함한").click()
    page.get_by_role("button", name="생성하기").click()
    page.get_by_role("button", name="생성하기").click()
    page.get_by_role("group").filter(has_text="사설 IP 설정VPC 및 Subnet").get_by_test_id("text-input-container").dblclick()
    page.locator("input[name=\"ipAddress\"]").fill("192.168.0.1")
    page.get_by_role("button", name="생성하기").click()
    page.get_by_label("Network Interface(NIC) 생성").get_by_role("button", name="x").click()
    page.locator("button").filter(has_text="신규 NIC 생성").click()
    page.get_by_placeholder("NIC 이름을 입력해주세요").click()
    page.locator("input[name=\"name\"]").fill("nic-01")
    page.locator(".s-checkbox.s-checkbox--medium.s-checkbox--default.s-checkbox--hover > .s-checkbox__input-wrapper > .s-checkbox__checkmark").click()
    page.get_by_role("button", name="생성하기").click()
    page.get_by_role("radio", name="nic-01 c808e989-a2f2-4dbd-").click()
    page.get_by_role("combobox", name="선택하세요").click()
    page.locator("button").filter(has_text="Key Pair 생성").click()
    page.get_by_role("dialog", name="Key Pair 생성").get_by_test_id("text-input-container").click()
    page.get_by_role("dialog", name="Key Pair 생성").get_by_label("input").fill("key-a")
    page.get_by_role("button", name="생성", exact=True).click()
    page.get_by_role("button", name="닫기").click()
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_text("key-a (24:d1:31:95:61:32:96:").click()
    page.get_by_role("button", name="서버 생성").click()
    page.get_by_text("생성중").first.click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

    """
    1) 서버 네비게이션 클릭으로 서버 페이지 진입
    2) 서버 생성 버튼 클릭
    3) 서버 이미지 선택
    page.get_by_role("radio", name="windows-2019-mssql-2017-std-").click()
    4) 서버 스펙 선택
    page.get_by_role("radio", name="32x32-amd 32 32 미정 미정").click()
    5-1) 서버 기본정보의 Avaliability Zone 선택
    page.get_by_role("combobox").click()
    page.get_by_role("option", name="DX-G-GB-A").click()
    5-2) 서버 기본정보의 서버 이름 입력
    page.get_by_role("textbox", name="input").fill("server-name-01")
    6) Volume 생성
    page.locator("button").filter(has_text="Volume 생성").click()
    page.locator("input[name=\"name\"]").fill("vo-01")
    page.locator("input[name=\"description\"]").fill("vo-01 desc")
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_text("Data Volume : be 1 (block").click()
    page.get_by_role("dialog", name="Volume 생성").locator("input[name=\"size\"]").fill("128")
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_test_id("s-select-option-list").get_by_text("DX-G-GB-A").click()
    page.get_by_role("button", name="확인").click()
    page.get_by_text("Volume 생성 성공") - 확인 토스트
    7) Volume 선택
    page.get_by_role("checkbox", name="vo-01 84592172-f1e6-4b59-b4f7").click() - name 바뀔것
    8) vpc 선택
    9) subnet 선택
    page.locator("button").filter(has_text="Subnet 생성").click()
    page.get_by_placeholder("Subnet 이름을 입력해주세요").click()
    page.locator("input[name=\"name\"]").fill("sub-name-01")
    page.get_by_placeholder("Subnet CIDR을 입력해주세요").click()
    page.locator("input[name=\"cidr\"]").fill("10.0.0.0/8")
    page.get_by_role("button", name="확인").click()
    page.get_by_text("Subnet 생성 성공") - 확인
    page.get_by_role("combobox").filter(has_text="subnet 선택").click()
    page.get_by_text("sub-name-01 (10.0.0.0/8)").click()
    9) 신규 nic 생성 및 선택
    page.locator("button").filter(has_text="신규 NIC 생성").click()
    page.locator("input[name=\"name\"]").fill("net-inter-01")
    page.locator(".s-checkbox.s-checkbox--medium.s-checkbox--default.s-checkbox--hover > .s-checkbox__input-wrapper > .s-checkbox__checkmark").click()
    page.get_by_role("dialog", name="Network Interface(NIC) 생성").click()
    10) keypair 생성 및 선택
    page.get_by_role("dialog", name="Key Pair 생성").get_by_label("input").fill("key-a")
    page.get_by_role("button", name="생성", exact=True).click()
    page.get_by_role("combobox", name="선택하세요").click()
    page.get_by_text("key-a (24:d1:31:95:61:32:96:").click()
    11) 서버 생성
    page.get_by_role("button", name="서버 생성").click()
    """
