class SidebarLocators:
    SERVER_MENU = "Server"
    NIC_MENU = "NIC (Network Interface)"
    KP_MENU = "Key Pair"
    VPC_MENU = "VPC"
    SUBNET_MENU = "Subnet"
    RT_MENU = "Route tables"
    NAT_MENU = "NAT Gateway"
    VPC_P_MENU = "VPC Peering"
    FIP_MENU = "Floating IP"
    IG_MENU = "Internet Gateway"
    NACL_MENU = "Network ACL"
    SG_MENU = "Security Groups"
    LOAD_BALANCER = "Load Balancer"
    VOLUME_MENU = "Volume"

class CreateButtonLocators:
    SERVER_CREATE = "Server 생성"
    NIC_CREATE = "NIC 생성"
    KP_CREATE = "Key Pair 생성"
    VPC_CREATE = "VPC 생성"
    SUBNET_CREATE = "Subnet 생성"
    RT_CREATE = "Route Tables 생성"
    NAT_CREATE = "NAT Gateway 생성"
    VPC_PEERING_CREATE = "VPC Peering 생성"
    FIP_CREATE = "Floating IP 생성"
    IG_CREATE = "Internet Gateway 생성"
    NACL_CREATE = "네트워크 ACL 생성"
    SG_CREATE = "Security Group 생성"
    LOAD_BALANCER_CREATE = "Load Balancer 생성"
    VOLUME_CREATE = "Volume 생성"