class SidebarLocators:
    ADMIN_MENU = "ADMIN"

    # 콘솔
    SERVER_MENU = "Server"
    NIC_MENU = "NIC (Network Interface)"
    KP_MENU = "Key Pair"
    VPC_MENU = "VPC"
    SUBNET_MENU = "Subnet"
    RUT_MENU = "Route tables"
    NAT_MENU = "NAT Gateway"
    VPC_P_MENU = "VPC Peering"
    FIP_MENU = "Floating IP"
    IG_MENU = "Internet Gateway"
    NACL_MENU = "Network ACL"
    SG_MENU = "Security Groups"
    LOAD_BALANCER = "Load Balancer"
    VOLUME_MENU = "Disk"
    SNAP_MENU = "Disk Snapshot"

    # 관리자 페이지
    MANAGE_PROJECT_MENU = "프로젝트 관리"
    USER_MENU = "사용자"
    USER_GROUP_MENU = "사용자 그룹"
    ROLE_MENU = "역할"
    MANAGE_ORG_MENU = "조직 정보 관리"

class CreateButtonLocators:
    SERVER_CREATE = "Server 생성"
    NIC_CREATE = "NIC 생성"
    KP_CREATE = "Key Pair 생성"
    VPC_CREATE = "VPC 생성"
    SUBNET_CREATE = "Subnet 생성"
    RUT_CREATE = "Route Tables 생성"
    NAT_CREATE = "NAT Gateway 생성"
    VPC_PEERING_CREATE = "VPC Peering 생성"
    FIP_CREATE = "Floating IP 생성"
    IG_CREATE = "Internet Gateway 생성"
    NACL_CREATE = "네트워크 ACL 생성"
    SG_CREATE = "Security Group 생성"
    LOAD_BALANCER_CREATE = "Load Balancer 생성"
    VOLUME_CREATE = "Volume 생성"
    PROJECT_CREATE = "프로젝트 생성"
    USER_CREATE = "사용자 생성"
    USER_GROUP_CREATE = "사용자 그룹 생성"